In [29]:
#first we import all the required libraries
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler

In [3]:
#Now we mount our drive
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive

In [30]:
#Reading the data from the dataset and converting it to a Pandas dataframe
df=pd.read_csv('gdrive/My Drive/Dataset.txt')

In [31]:
#Outputting our dataframe
df

        duration protocol_type  ... attack_category occurance
0              0           tcp  ...          normal        20
1              0           udp  ...          normal        15
2              0           tcp  ...         neptune        19
3              0           tcp  ...          normal        21
4              0           tcp  ...          normal        21
...          ...           ...  ...             ...       ...
125968         0           tcp  ...         neptune        20
125969         8           udp  ...          normal        21
125970         0           tcp  ...          normal        18
125971         0           tcp  ...         neptune        20
125972         0           tcp  ...          normal        21

[125973 rows x 43 columns]

In [32]:
#this will show us only first five rows of the dataframe
df.head()

   duration protocol_type  ... attack_category occurance
0         0           tcp  ...          normal        20
1         0           udp  ...          normal        15
2         0           tcp  ...         neptune        19
3         0           tcp  ...          normal        21
4         0           tcp  ...          normal        21

[5 rows x 43 columns]

In [33]:
#Outputting the columns of our dataframe
df.columns

Index(['duration', 'protocol_type', 'service', 'flag', 'src_bytes',
       'dst_bytes', 'land', 'wrong_fragment', 'urgent', 'hot',
       'num_failed_logins', 'logged_in', 'num_compromised', 'root_shell',
       'su_attempted', 'num_root', 'num_file_creations', 'num_shells',
       'num_access_files', 'num_outbound_cmds', 'is_host_login',
       'is_guest_login', 'count', 'srv_count', 'serror_rate',
       'srv_serror_rate', 'rerror_rate', 'srv_rerror_rate', 'same_srv_rate',
       'diff_srv_rate', 'srv_diff_host_rate', 'dst_host_count',
       'dst_host_srv_count', 'dst_host_same_srv_rate',
       'dst_host_diff_srv_rate', 'dst_host_same_src_port_rate',
       'dst_host_srv_diff_host_rate', 'dst_host_serror_rate',
       'dst_host_srv_serror_rate', 'dst_host_rerror_rate',
       'dst_host_srv_rerror_rate', 'attack_category', 'occurance'],
      dtype='object')

In [34]:
#Uploading the file from local drive
#The size of the file is very small so we can easily upload it from the local drive
from google.colab import files
uploaded = files.upload()

Saving Attack_types.txt to Attack_types (1).txt

In [35]:
#Reading the file and converting it to Pandas dataframe
import io
df_t = pd.read_csv(io.BytesIO(uploaded['Attack_types.txt']))

In [36]:
#Mapping each attribute to an attack type. We have 4 attack types and a normal category
mapped_attack = [x.strip().split() for x in open('Attack_types.txt', 'r')]
mapped_attack = {a:b for (a,b) in mapped_attack}

In [37]:
#Visualizing our attack map
mapped_attack

{'apache2': 'dos',
 'attack_category': 'attack_type',
 'back': 'dos',
 'buffer_overflow': 'u2r',
 'ftp_write': 'r2l',
 'guess_passwd': 'r2l',
 'httptunnel': 'u2r',
 'imap': 'r2l',
 'ipsweep': 'probe',
 'land': 'dos',
 'loadmodule': 'u2r',
 'mailbomb': 'dos',
 'mscan': 'probe',
 'multihop': 'r2l',
 'named': 'r2l',
 'neptune': 'dos',
 'nmap': 'probe',
 'perl': 'u2r',
 'phf': 'r2l',
 'pod': 'dos',
 'portsweep': 'probe',
 'processtable': 'dos',
 'ps': 'u2r',
 'rootkit': 'u2r',
 'saint': 'probe',
 'satan': 'probe',
 'sendmail': 'r2l',
 'smurf': 'dos',
 'snmpgetattack': 'dos',
 'snmpguess': 'r2l',
 'spy': 'r2l',
 'sqlattack': 'u2r',
 'teardrop': 'dos',
 'udpstorm': 'dos',
 'warezclient': 'r2l',
 'warezmaster': 'r2l',
 'worm': 'probe',
 'xlock': 'r2l',
 'xsnoop': 'r2l',
 'xterm': 'u2r'}

In [38]:
#Replacing the attack_category from the datafram of Dataset by the types of attacks in the attack_map
df['attack_category'] = df['attack_category'].replace(mapped_attack)

In [39]:
#encoding the categorical values from the dataframe and replacing them with dummy numerical values
def cat_encoding(df1, col1):
    return pd.concat([df1.drop(col1, axis=1), pd.get_dummies(df1[col1].values)], axis=1)

In [40]:
#Some of the values in the dataframe are very wide in range. Such as duration, Source bytes and Desination Bytes.
#To concatenate them in a small range, we do the log scalling.
def log_scalling(df1, col1):
    return df1[col1].apply(np.log1p)

In [41]:
#Catagorical Values
cat_list = ['protocol_type', 'service', 'flag']
for col in cat_list:
    df = cat_encoding(df, col)

In [42]:
#Log scalling values
log_list = ['duration', 'src_bytes', 'dst_bytes']
for col in log_list:
    df[col] = log_scalling(df, col)

In [43]:
df.head()

   duration  src_bytes  dst_bytes  land  wrong_fragment  ...  S1  S2  S3  SF  SH
0       0.0   6.198479   0.000000     0               0  ...   0   0   0   1   0
1       0.0   4.990433   0.000000     0               0  ...   0   0   0   1   0
2       0.0   0.000000   0.000000     0               0  ...   0   0   0   0   0
3       0.0   5.451038   9.006264     0               0  ...   0   0   0   1   0
4       0.0   5.298317   6.042633     0               0  ...   0   0   0   1   0

[5 rows x 124 columns]

In [44]:
df.columns

Index(['duration', 'src_bytes', 'dst_bytes', 'land', 'wrong_fragment',
       'urgent', 'hot', 'num_failed_logins', 'logged_in', 'num_compromised',
       ...
       'REJ', 'RSTO', 'RSTOS0', 'RSTR', 'S0', 'S1', 'S2', 'S3', 'SF', 'SH'],
      dtype='object', length=124)

In [45]:
#Saving the attack_category labels in target variable and dropping the values in the column afterwards.
target_var = df.pop('attack_category')

In [46]:
#Getting dummy values
target_var = pd.get_dummies(target_var)

In [47]:
target_var

        dos  normal  probe  r2l  u2r
0         0       1      0    0    0
1         0       1      0    0    0
2         1       0      0    0    0
3         0       1      0    0    0
4         0       1      0    0    0
...     ...     ...    ...  ...  ...
125968    1       0      0    0    0
125969    0       1      0    0    0
125970    0       1      0    0    0
125971    1       0      0    0    0
125972    0       1      0    0    0

[125973 rows x 5 columns]

In [48]:
#Preparing two variables for training of our model.
target_var = target_var.values
train = df.values

In [49]:
#Transform all the features in the range of 0 and 1 which is the default value of MinMaxScaler
min_max_scaler = MinMaxScaler()
train = min_max_scaler.fit_transform(train)

In [50]:
train.shape

(125973, 123)

In [51]:
#Importing all the required libraries for building the model.
from keras.callbacks import EarlyStopping
from keras.models import Sequential
from keras.layers import Dense, Activation
from keras.layers.embeddings import Embedding

**This is our Model 1**
It has 6 total layers. All the layers have ReLU activation except for the last one which has a 5 way sofmax activation function because we have 5 classes to predict.
The 1st layer has 128 neurons.
The 2nd layer has 16 neurons.
The 3rd layer has 256 neurons.
The 4th layer has 128 neurons.
The 5th layer has 32 neurons.
The 6th layer has 5 neurons.
**The Batch size is 128 and the validation split used is 0.1.**
**The optimizer used is Adam.**
**Epochs are 10**

In [52]:
#Building the network through keras framework
def build_network():
    models = []
    model = Sequential()
    model.add(Dense(128, input_dim=123))
    model.add(Activation('relu'))
    model.add(Dense(16))
    model.add(Activation('relu'))
    model.add(Dense(256))
    model.add(Activation('relu'))
    model.add(Dense(128))
    model.add(Activation('relu'))
    model.add(Dense(32))
    model.add(Activation('relu'))
    model.add(Dense(5))
    model.add(Activation('softmax'))

    model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

    return model

In [53]:
#Early stopping
network = build_network()
early_stopping = EarlyStopping(monitor='val_loss', min_delta=0, patience=3, verbose=0, mode='auto')

In [54]:
#Runnig the model
network.fit(x=train, y=target_var, epochs=10, validation_split=0.1, batch_size=128, callbacks=[early_stopping])

Epoch 1/10
886/886 [==============================] - 5s 5ms/step - loss: 0.2007 - accuracy: 0.9563 - val_loss: 0.0133 - val_accuracy: 0.9952
Epoch 2/10
886/886 [==============================] - 4s 4ms/step - loss: 0.0117 - accuracy: 0.9960 - val_loss: 0.0099 - val_accuracy: 0.9960
Epoch 3/10
886/886 [==============================] - 4s 4ms/step - loss: 0.0071 - accuracy: 0.9975 - val_loss: 0.0123 - val_accuracy: 0.9960
Epoch 4/10
886/886 [==============================] - 3s 4ms/step - loss: 0.0072 - accuracy: 0.9977 - val_loss: 0.0056 - val_accuracy: 0.9979
Epoch 5/10
886/886 [==============================] - 3s 4ms/step - loss: 0.0046 - accuracy: 0.9985 - val_loss: 0.0058 - val_accuracy: 0.9972
Epoch 6/10
886/886 [==============================] - 4s 4ms/step - loss: 0.0040 - accuracy: 0.9987 - val_loss: 0.0037 - val_accuracy: 0.9990
Epoch 7/10
886/886 [==============================] - 3s 4ms/step - loss: 0.0038 - accuracy: 0.9988 - val_loss: 0.0048 - val_accuracy: 0.9987
Epoch 8/10
886/886 [==============================] - 4s 4ms/step - loss: 0.0037 - accuracy: 0.9989 - val_loss: 0.0042 - val_accuracy: 0.9990
Epoch 9/10
886/886 [==============================] - 4s 4ms/step - loss: 0.0031 - accuracy: 0.9990 - val_loss: 0.0040 - val_accuracy: 0.9988

**This is our Model 2**
It has 4 total layers. All the layers have ReLU activation except for the last one which has a 5 way sofmax activation function because we have 5 classes to predict.
The 1st layer has 128 neurons.
The 2nd layer has 256 neurons.
The 3rd layer has 64 neurons.
The 4th layer has 5 neurons.
**The Batch size is 128 and the validation split used is 0.2.**
**The optimizer used is Adam.**
**Epochs are 15**

In [55]:
def build_network():
    models = []
    model = Sequential()
    model.add(Dense(128, input_dim=123))
    model.add(Activation('relu'))
    model.add(Dense(128))
    model.add(Activation('relu'))
    model.add(Dense(64))
    model.add(Activation('relu'))
    model.add(Dense(5))
    model.add(Activation('softmax'))

    model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

    return model

In [56]:
network = build_network()
early_stopping = EarlyStopping(monitor='val_loss', min_delta=0, patience=3, verbose=0, mode='auto')

In [57]:
network.fit(x=train, y=target_var, epochs=15, validation_split=0.2, batch_size=128, callbacks=[early_stopping])

Epoch 1/15
788/788 [==============================] - 3s 3ms/step - loss: 0.1829 - accuracy: 0.9551 - val_loss: 0.0110 - val_accuracy: 0.9963
Epoch 2/15
788/788 [==============================] - 2s 3ms/step - loss: 0.0106 - accuracy: 0.9966 - val_loss: 0.0098 - val_accuracy: 0.9972
Epoch 3/15
788/788 [==============================] - 2s 3ms/step - loss: 0.0074 - accuracy: 0.9976 - val_loss: 0.0067 - val_accuracy: 0.9982
Epoch 4/15
788/788 [==============================] - 2s 3ms/step - loss: 0.0080 - accuracy: 0.9974 - val_loss: 0.0052 - val_accuracy: 0.9987
Epoch 5/15
788/788 [==============================] - 2s 3ms/step - loss: 0.0043 - accuracy: 0.9986 - val_loss: 0.0050 - val_accuracy: 0.9985
Epoch 6/15
788/788 [==============================] - 2s 3ms/step - loss: 0.0040 - accuracy: 0.9988 - val_loss: 0.0045 - val_accuracy: 0.9990
Epoch 7/15
788/788 [==============================] - 2s 3ms/step - loss: 0.0032 - accuracy: 0.9990 - val_loss: 0.0039 - val_accuracy: 0.9990
Epoch 8/15
788/788 [==============================] - 2s 3ms/step - loss: 0.0035 - accuracy: 0.9988 - val_loss: 0.0028 - val_accuracy: 0.9991
Epoch 9/15
788/788 [==============================] - 2s 3ms/step - loss: 0.0024 - accuracy: 0.9992 - val_loss: 0.0036 - val_accuracy: 0.9984
Epoch 10/15
788/788 [==============================] - 2s 3ms/step - loss: 0.0026 - accuracy: 0.9991 - val_loss: 0.0038 - val_accuracy: 0.9991
Epoch 11/15
788/788 [==============================] - 2s 3ms/step - loss: 0.0029 - accuracy: 0.9992 - val_loss: 0.0038 - val_accuracy: 0.9990

**This is our Model 3**
It has 4 total layers. All the layers have ReLU activation except for the last one which has a 5 way sofmax activation function because we have 5 classes to predict.
The 1st layer has 128 neurons.
The 2nd layer has 32 neurons.
The 3rd layer has 128 neurons.
The 4th layer has 5 neurons.
**The Batch size is 64 and the validation split used is 0.1.**
**The optimizer used is Adam.**
**Epochs are 20**

In [58]:
def build_network():
    models = []
    model = Sequential()
    model.add(Dense(128, input_dim=123))
    model.add(Activation('relu'))
    model.add(Dense(32))
    model.add(Activation('relu'))
    model.add(Dense(128))
    model.add(Activation('relu'))
    model.add(Dense(5))
    model.add(Activation('softmax'))

    model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

    return model

In [59]:
network = build_network()
early_stopping = EarlyStopping(monitor='val_loss', min_delta=0, patience=3, verbose=0, mode='auto')

In [60]:
network.fit(x=train, y=target_var, epochs=20, validation_split=0.1, batch_size=64, callbacks=[early_stopping])

Epoch 1/20
1772/1772 [==============================] - 4s 2ms/step - loss: 0.1531 - accuracy: 0.9604 - val_loss: 0.0172 - val_accuracy: 0.9928
Epoch 2/20
1772/1772 [==============================] - 3s 2ms/step - loss: 0.0110 - accuracy: 0.9958 - val_loss: 0.0103 - val_accuracy: 0.9964
Epoch 3/20
1772/1772 [==============================] - 4s 2ms/step - loss: 0.0080 - accuracy: 0.9971 - val_loss: 0.0060 - val_accuracy: 0.9979
Epoch 4/20
1772/1772 [==============================] - 3s 2ms/step - loss: 0.0063 - accuracy: 0.9979 - val_loss: 0.0040 - val_accuracy: 0.9990
Epoch 5/20
1772/1772 [==============================] - 4s 2ms/step - loss: 0.0048 - accuracy: 0.9984 - val_loss: 0.0045 - val_accuracy: 0.9988
Epoch 6/20
1772/1772 [==============================] - 4s 2ms/step - loss: 0.0041 - accuracy: 0.9986 - val_loss: 0.0034 - val_accuracy: 0.9988
Epoch 7/20
1772/1772 [==============================] - 3s 2ms/step - loss: 0.0033 - accuracy: 0.9989 - val_loss: 0.0065 - val_accuracy: 0.9981
Epoch 8/20
1772/1772 [==============================] - 3s 2ms/step - loss: 0.0031 - accuracy: 0.9990 - val_loss: 0.0041 - val_accuracy: 0.9984
Epoch 9/20
1772/1772 [==============================] - 3s 2ms/step - loss: 0.0029 - accuracy: 0.9990 - val_loss: 0.0042 - val_accuracy: 0.9989